/** Shared opacity levels for native-style triggers. */
export const NATIVE_TRIGGER_LABEL_OPACITY = 0.58;
export const NATIVE_TRIGGER_DISABLE_OPACITY = 0.5;
export const NATIVE_TRIGGER_PRESS_OPACITY = 0.6;
export const NATIVE_TRIGGER_WEB_PRESS_OPACITY = 0.6;
export const NATIVE_TRIGGER_WEB_HOVER_OPACITY = 0.7;

// Component-specific aliases keep the values discoverable at each call site
// while ensuring Select and Dropdown cannot drift apart.
export const SELECT_TRIGGER_DISABLE_OPACITY = NATIVE_TRIGGER_DISABLE_OPACITY;
export const SELECT_TRIGGER_PRESS_OPACITY = NATIVE_TRIGGER_PRESS_OPACITY;
export const SELECT_TRIGGER_WEB_PRESS_OPACITY = NATIVE_TRIGGER_WEB_PRESS_OPACITY;
export const SELECT_TRIGGER_WEB_HOVER_OPACITY = NATIVE_TRIGGER_WEB_HOVER_OPACITY;
export const DROPDOWN_TRIGGER_DISABLE_OPACITY = NATIVE_TRIGGER_DISABLE_OPACITY;
export const DROPDOWN_TRIGGER_PRESS_OPACITY = NATIVE_TRIGGER_PRESS_OPACITY;
export const DROPDOWN_TRIGGER_WEB_PRESS_OPACITY = NATIVE_TRIGGER_WEB_PRESS_OPACITY;
export const DROPDOWN_TRIGGER_WEB_HOVER_OPACITY = NATIVE_TRIGGER_WEB_HOVER_OPACITY;
